### PR TITLE
Handle .NET 5+ single-file applications

### LINKED ISSUE #28: Not working with /p:PublishSingleFile=true apps
If a project is built as a single file:

```bash
dotnet publish -c Release -r win-x86 /p:PublishSingleFile=true
zip -j $zip_file ./bin/Release/netcoreapp3.1/win-x86/publish/myapp.exe
```

then the app is not updated with this code:

```cs
using (var manager = new UpdateManager(
	new WebPackageResolver(Config.update_manifest_url),
	new ZipPackageExtractor()))
{
	var result = await manager.CheckForUpdatesAsync();
	if (result.CanUpdate)
	{
		// Prepare an update by downloading and extracting the package
		// (supports progress reporting and cancellation)
		await manager.PrepareUpdateAsync(result.LastVersion);

		// Launch an executable that will apply the update
		// (can be instructed to restart the application afterwards)
		manager.LaunchUpdater(result.LastVersion);

		// Terminate the running application so that the updater can overwrite files
		Environment.Exit(0);
	}
}
```

It correctly detects the new version, downloads it, runs LaunchUpdater, but the actual file is not replaced with the new version. It works fine without `/p:PublishSingleFile=true`.

### PR DESCRIPTION
**Pull request by 0xced**
Detecting when an application is published as a single executable by testing if the entry assembly `Location` is empty.

Fixes #28

### CODE REVIEW

File: Onova/Models/AssemblyMetadata.cs [hunk 1]
```diff
@@ -49,14 +50,29 @@ public partial class AssemblyMetadata
...
+        var assembly = Assembly.GetEntryAssembly() ?? throw new InvalidOperationException("Can't get entry assembly.");
+        if (string.IsNullOrEmpty(assembly.Location))
+        {
+            // The assembly was published as a [single executable](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview)
+            // Location returning an empty string is [documented](https://learn.microsoft.com/en-us/dotnet/api/System.Reflection.Assembly.Location#remarks)
+            // > In .NET 5 and later versions, for bundled assemblies, the value returned is an empty string.
+            return FromAssembly(assembly, Process.GetCurrentProcess().MainModule?.FileName ?? throw new InvalidOperationException("Can't get current process main module."));
+        }
+        return FromAssembly(assembly, assembly.Location);
+    }
```
Comment (Tyrrrz) [inline Onova/Models/AssemblyMetadata.cs:77]: Can we rewrite this like so...

```suggestion
    public static AssemblyMetadata FromEntryAssembly()
    {
        // For regular applications, the entry assembly is the entry point
        var assembly =
            Assembly.GetEntryAssembly() ??
            throw new InvalidOperationException("Can't get entry assembly.");

        if (!string.IsNullOrWhiteSpace(assembly.Location))
            return FromAssembly(assembly, assembly.Location);

        // For self-contained applications, the entry point is the executable
        var filePath =
            Process.GetCurrentProcess().MainModule?.FileName ??
            throw new InvalidOperationException("Can't get current process main module.")

        return FromAssembly(assembly, filePath);
    }
```

File: Onova/Models/AssemblyMetadata.cs [hunk 2]
```diff
@@ -49,14 +50,29 @@ public partial class AssemblyMetadata
...
-        FromAssembly(assembly, assembly.Location);
+    public static AssemblyMetadata FromAssembly(Assembly assembly)
+    {
+        if (string.IsNullOrEmpty(assembly.Location))
+        {
+            throw new InvalidOperationException($"The location of assembly {assembly.GetName().FullName} could not be determined. " +
+                                                "Use AssemblyMetadata.FromAssembly(Assembly assembly, string assemblyFilePath) method instead");
+        }
+        return FromAssembly(assembly, assembly.Location);
+    }
```
Comment (Tyrrrz) [inline Onova/Models/AssemblyMetadata.cs:61]:
```suggestion
    public static AssemblyMetadata FromAssembly(Assembly assembly)
    {
        if (string.IsNullOrEmpty(assembly.Location))
        {
            throw new InvalidOperationException(
                $"The location of assembly {assembly.GetName().FullName} could not be determined. " +
                "Use the `AssemblyMetadata.FromAssembly(Assembly assembly, string assemblyFilePath)` method to provide it explicitly.");
        }

        return FromAssembly(assembly, assembly.Location);
    }
```

**Review by Tyrrrz — COMMENTED** [review]
Some cosmetic cleanup

**Comment by 0xced** [comment]
I just applied both cosmetic cleanup suggestions.

Also, letting this here for the record:
* [Single-file deployment and executable](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview) official documentation
* [Assembly.Location](https://learn.microsoft.com/en-us/dotnet/api/System.Reflection.Assembly.Location#remarks) official documentation:
  > In .NET 5 and later versions, for bundled assemblies, the value returned is an empty string.

**Comment by Tyrrrz** [comment]
Thanks a lot!

**Comment by 0xced** [comment]
Thanks for merging! Do you plan to release a new version with that bug fix anytime soon?

**Comment by Tyrrrz** [comment]
> Thanks for merging! Do you plan to release a new version with that bug fix anytime soon?

Sure I'll release it today
